// GENERATED by scripts/gen-deployment.mjs from deployments/bhutan-luxe.json — do not edit.
//
// The environment this build reads, gathered from the kernel and the entities
// this deployment installs. A client hosting the product themselves needs to
// know what to configure, and the answer depends on which entities they took
// (ADR 0001) — so the list is generated rather than written down once and left
// to drift. Internal code is skipped: its variables are Edge8's own business
// and this file ships.
//
// REQUIRED is what `requireEnv` throws without. OPTIONAL is read through
// `optionalEnv` or straight off `process.env`, where the code has a defined
// answer when it is unset — a feature that stays off rather than a broken boot.
//
// Regenerate with `npm run gen:deployment`; `npm run check:generated` fails
// when this file and the deployment disagree.

export const REQUIRED_ENV = [
  "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
  "NEXT_PUBLIC_SUPABASE_URL",
  "STRIPE_SECRET_KEY",
] as const;

/**
 * Read through `optionalEnv` or straight off `process.env`. Nothing imports
 * it — it is the configuration list a self-hosting client reads, not a runtime
 * value — so knip is told to leave it alone.
 * @generator
 */
export const OPTIONAL_ENV = [
  "ACCESS_GATE_SECRET",
  "ACCOUNTING_EMAIL",
  "ADMIN_ALLOWLIST",
  "ADMIN_EMAILS",
  "ANTHROPIC_API_KEY",
  "ANTHROPIC_TIMEOUT_MS",
  "CHATBOT_PRIVILEGED_EMAILS",
  "CHATBOT_WRITE_DB_URL",
  "CRON_SECRET",
  "EMAIL_FROM",
  "EMAIL_SIGN_OFF",
  "EVENTS_EMAIL",
  "HR_ALERT_EMAIL",
  "INQUIRY_INGEST_SECRET",
  "LARK_API_BASE",
  "LARK_API_HOST",
  "LARK_APP_ID",
  "LARK_APP_SECRET",
  "LARK_COACHING_WEBHOOK_URL",
  "LARK_EO_WEBHOOK_URL",
  "LARK_MARKETING_WEBHOOK_URL",
  "LARK_OPS_WEBHOOK_URL",
  "LARK_PRODUCT_WEBHOOK_URL",
  "NEXT_PUBLIC_LARK_WORKSPACE_URL",
  "NEXT_PUBLIC_LEGAL_ENTITY_NAME",
  "NEXT_PUBLIC_ONBOARDING_DECK_URL",
  "NEXT_PUBLIC_ORG_ALTERNATE_NAME",
  "NEXT_PUBLIC_ORG_DESCRIPTION",
  "NEXT_PUBLIC_ORG_FOUNDER",
  "NEXT_PUBLIC_ORG_NAME",
  "NEXT_PUBLIC_ORG_SALES_EMAIL",
  "NEXT_PUBLIC_ORG_SAME_AS",
  "NEXT_PUBLIC_SITE_URL",
  "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  "NEXT_PUBLIC_SUPPORT_EMAIL",
  "NODE_ENV",
  "OPS_EMAIL",
  "QBO_CLIENT_ID",
  "QBO_CLIENT_SECRET",
  "QBO_ENV",
  "QBO_REALM_ID",
  "QBO_REDIRECT_URI",
  "QBO_SERVICE_ITEM_ID",
  "RESEND_API_KEY",
  "RESEND_WEBHOOK_SECRET",
  "SENSITIVE_VIEWERS",
  "STRIPE_SECRET_TEST_KEY",
  "STRIPE_WEBHOOK_SECRET",
  "STRIPE_WEBHOOK_TEST_SECRET",
  "SUPABASE_SECRET_KEY",
  "SUPABASE_URL",
  "TELEGRAM_BOT_TOKEN",
  "TELEGRAM_CHAT_ID",
  "VERCEL_ANALYTICS_TOKEN",
  "X",
] as const;

/** The required variables this process is missing, for a boot-time report. */
export function missingDeploymentEnv(): string[] {
  return REQUIRED_ENV.filter((name) => {
    const value = process.env[name];
    return value === undefined || value === "";
  });
}
