// GENERATED by scripts/gen-app-mounts.mjs — do not edit.
// The body lives in entities/billing/routes/checkout/layout; this file
// exists because Next binds a route by the exports of the file under app/.
// Anything below that a re-export cannot carry is declared by the entity, in
// its mounts.ts.
import "@/app/(admin)/styles/site-components.css";
import "@/app/(admin)/styles/utilities.css";
export { default } from "@/entities/billing/routes/checkout/layout";
